openapi: 3.1.0
x-stoplight:
  id: altylcuys382t
info:
  title: Brachio
  version: '1.0'
  summary: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    x-stoplight:
                      id: m28cjc2m49fb3
                  name:
                    type: string
                    x-stoplight:
                      id: 45xk4l2430m9p
                  email:
                    type: string
                    x-stoplight:
                      id: f7sa9pcgo2cl7
              examples:
                Example 1:
                  value:
                    id: 0
                    name: string
                    email: string
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: uqtxvwp55j0qq
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                type: object
              examples:
                Example 1:
                  value:
                    id: 1
                    name: Smith
                    email: alice.smith@gmail.com
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  x-stoplight:
                    id: p4ubm1ilbku9g
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
            examples:
              Update Name:
                value:
                  name: name
              Update Email:
                value:
                  email: rebecca@gmail.com
        description: Patch user properties to update.
      x-stoplight:
        id: m7ope66kuoywf
  /signup:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '201':
          description: User Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    x-stoplight:
                      id: 8kr97jesx01z5
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - hashed_password
              properties:
                name:
                  type: string
                  x-stoplight:
                    id: 0hiiiwuxq7wx0
                email:
                  type: string
                  x-stoplight:
                    id: ahmsccrh67t7o
                hashed_password:
                  type: string
                  x-stoplight:
                    id: 237xrtywn9vnh
            examples:
              Example 1:
                value:
                  name: string
                  email: string
                  hashed_password: string
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: hd45gduays3lf
    parameters: []
  /media:
    get:
      summary: Get Media Info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  medium:
                    x-stoplight:
                      id: hie6gpwholc0l
                    type: array
                    items: {}
              examples:
                Example 2:
                  value:
                    medium:
                      - id: 0
                        user_id: string
                        image_url: string
                        movie_url: string
                        lat: string
                        lon: string
                      - id: 0
                        user_id: string
                        image_url: string
                        movie_url: string
                        lat: string
                        lon: string
        '404':
          description: Not Found
      operationId: get-media
      x-stoplight:
        id: mjp2yqsnm5j00
      parameters: []
    post:
      summary: Create New Media
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
              examples:
                Example 1:
                  value:
                    medium:
                      - id: 1
                        user_id: 1
                        image_url: string
                        movie_url: string
                        lat: 0
                        lon: 0
                      - id: 2
                        user_id: 1
                        image_url: string
                        movie_url: string
                        lat: 0
                        lon: 0
      operationId: post-media
      x-stoplight:
        id: tmdk0ju8q9vv6
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                image_url:
                  type: string
                  x-stoplight:
                    id: tm7l3pdstk9b7
                movie_url:
                  type: string
                  x-stoplight:
                    id: 5efdazq5eqffq
                lat:
                  type: integer
                  x-stoplight:
                    id: jwluf4uststft
                lon:
                  type: integer
                  x-stoplight:
                    id: wanmowld6rv60
            examples:
              Example 1:
                value:
                  image_url: string
                  movie_url: string
                  lat: 0
                  lon: 0
    parameters: []
  '/media/{mediaId}':
    parameters:
      - schema:
          type: string
        name: mediaId
        in: path
        required: true
    delete:
      summary: Delete Media
      tags: []
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      operationId: delete-medium-mediaId
      x-stoplight:
        id: xlysklwg8w1e7
    patch:
      summary: Update Media Info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
              examples:
                Example 1:
                  value:
                    id: 0
                    user_id: string
                    image_url: string
                    movie_url: string
                    lat: string
                    lon: string
        '400':
          description: Bad Request
      operationId: patch-medium-mediaId
      x-stoplight:
        id: pifv0bih1zt4t
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                image_url:
                  type: string
                  x-stoplight:
                    id: 1np77bh2gy1p4
                movie_url:
                  type: string
                  x-stoplight:
                    id: haun73k7dcgtp
                lat:
                  type: integer
                  x-stoplight:
                    id: evnzrrjmsfigk
                lon:
                  type: integer
                  x-stoplight:
                    id: v2tzw13b1ok1s
            examples:
              Example 1:
                value:
                  image_url: string
                  movie_url: string
                  lat: 0
                  lon: 0
  /login:
    post:
      summary: Login
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    x-stoplight:
                      id: spj5dv253ad2q
              examples:
                Example 1:
                  value:
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMSIsIm5hbWUiOiJoYWtreSIsImVtYWlsIjoiaGFra3lAZW1haWwuY29tIn0.AvLXzyxzX4Jy0rzDcHWWQeMC57N4dGqf6sXyYQOkyEg
        '404':
          description: Not Found
      operationId: post-login
      x-stoplight:
        id: cl502l7hlhvdn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  x-stoplight:
                    id: 1ybb65l2awn7m
                password:
                  type: string
                  x-stoplight:
                    id: cjksd5e3q9kru
            examples:
              Example 1:
                value:
                  email: hoge@gmail.com
                  password: ecb666d778725ec97307044d642bf4d160aabb76f56c0069c71ea25b1e926825
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      examples:
        - id: 1
          name: hoge
          email: hoge@gmail.com
          hashed_password: ecb666d778725ec97307044d642bf4d160aabb76f56c0069c71ea25b1e926825
      x-stoplight:
        id: g4nkvzud6e9du
      required:
        - id
        - name
        - email
        - hashed_password
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: cql6amkua65zu
        name:
          type: string
          x-stoplight:
            id: ymixwmphppjhr
        email:
          type: string
          format: email
          x-stoplight:
            id: hcuka6cri5l9f
        hashed_password:
          type: string
          x-stoplight:
            id: 83x49tjnrcoka
    Media:
      title: Media
      x-stoplight:
        id: msyk1m161kwq7
      type: object
      required:
        - user_id
        - image_url
      properties:
        id:
          type: integer
          x-stoplight:
            id: qj0hqiejzjnhl
        user_id:
          type: integer
          x-stoplight:
            id: w6v0u4sqwpwcm
        image_url:
          type: string
          x-stoplight:
            id: 96rx865myi5nf
        movie_url:
          type: string
          x-stoplight:
            id: hzwkcxyma7iiu
        lat:
          type: integer
          x-stoplight:
            id: z97bw2nls8lum
        lon:
          type: integer
          x-stoplight:
            id: ozazezcyhc6ub
      examples:
        - id: 0
          user_id: 0
          image_url: 'http://hogehoge.com'
          movie_url: 'http://hogehoge.com'
          lat: 35.298739874
          lon: 136.02098938
  responses: {}
